# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13OBNk4m-VE7f2zrU8nopgLVcIb1xaZFl
"""

resposta = ('deseja ir a proxima tela')
if resposta =='sim':
  print('voce foi para outra tela')
else:
    print('voce saiu do sistema')

nome = input('informe o nome de usuario:')
sexo = input("informe'f'para feminino e 'm'para masculino: ").upper()
if(sexo == 'M'):
    sexo = 'o'
elif(sexo == 'F'):
    sexo = 'a'
usuario = int(input('imforme o tipo de usuario \n 1 - para administrador \n 2 - para usuario comum \n 3 - para membro associado'))
if(usuario == 1): 
    usuario = 'adminitrador do sistema'
elif(usuario == 3):
    usuario = 'membro assciado'
elif(usuario==2):
    usuario = "usuario comum"
else:
    usuario = 'não cadastrad'
print (f'seja bem vind{sexo} {nome},a sua lincença e de {usuario}')